BUG: multiple fixes
pieper/SlicerDICOMwebBrowser pull request #1
Opened 2022-01-27 19:43 UTC by deepakri201

With reference to: https://github.com/lassoan/SlicerDICOMwebBrowser/pull/7

I have made a number of changes with reference to the above pull request. This was only tested on a Windows machine, with Slicer version 4.11.20210226. 

1. I had to modify how the `gcloud` command was found

2. I added in checking of the `dicomweb_client` version to use either `load_json_dataset(serieJson)` if < 0.54 or  `pydicom.dataset.Dataset.from_json(serieJson)` if > 0.54. 

3. I added code so that the serverURL was populated, by adding this line `self.serverUrlLineEdit.currentText = qt.QSettings().value('DICOMwebBrowser/ServerURL', url) ` in `onGCPSelectorDialogFinished`

4. I modified how the projects, datasets and datastores were listed. The `gcloud` command on Windows results in separate lines  as seen in the image below. 
![listing_projects_windows_error](https://user-images.githubusercontent.com/59979551/151431405-c96c031d-6dce-4836-8130-e2913a099c1b.png)
When one project is clicked, it results in the following: 
![listing_projects_windows_error_2](https://user-images.githubusercontent.com/59979551/151431588-7929c467-43d3-4745-a110-457894f3afb9.png)
Instead, for listing the projects, we could format the output by using: `gcloud projects list --format="value(PROJECT_ID)" `
For the datasets and datastores, similar commands can be used.

2022-01-27 21:56 UTC, fedorov commented
I tested this branch on mac, and it worked for me - and now I am able to select the store, and the URL is populated based on that selection, unlike before!

Thank you @deepakri201!

2022-02-01 00:01 UTC, pieper requested changes
Thanks for the fixes!

Just a few nitpicky comments and some questions but nothing major.

Sorry I didn't see this before.  For some reason github didn't set me up to be notified of PRs to my own PR.

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    # from dicomweb_client.api import load_json_dataset
Let's not leave in dead code, but get rid of this if it's not needed anymore.

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    # from dicomweb_client.api import load_json_dataset
here too

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      # serie = load_json_dataset(serieJson)
and here

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    args = [shutil.which('gcloud')]
Hmm, I wouldn't have thought this would make a difference.  Are you sure it's needed?

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    return self.gcloud(f"--project {project} healthcare datasets list --format=value(ID,LOCATION)").split("\n")[0:]
The purpose of the [1:] was to strip off the header line, which isn't a selectable project - don't you still want to do that?

Also [:0] is a no-op I believe.

2022-02-01 00:01 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      if (version.parse(dicomweb_client.__version__) < version.parse("0.54")):
I'd want to avoid supporting old versions of the library.  If this is needed to support only the 4.11 version of Slicer we should put in a comment to that effect so that we'll know we can remove it when Slicer 5 is released.

2022-02-01 16:43 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    args = [shutil.which('gcloud')]
I think it is; I've attached a screenshot to show the error I get when using `args = ['gcloud']` vs the new way.
![error_finding_gcloud2](https://user-images.githubusercontent.com/59979551/152011498-8b17856f-1e1c-4ce0-85d6-8cccf224922f.JPG)

2022-02-01 16:54 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    return self.gcloud(f"--project {project} healthcare datasets list --format=value(ID,LOCATION)").split("\n")[0:]
I believe that there was no header line when I listed the projects:
![error_listing_projects](https://user-images.githubusercontent.com/59979551/152013501-fcbbfc51-4c95-4f62-9512-fe8efe328170.JPG)

2022-02-01 16:54 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    return self.gcloud(f"--project {project} healthcare datasets list --format=value(ID,LOCATION)").split("\n")[0:]
Sorry, yes I have removed all instances of [0:].

2022-02-01 16:58 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    # from dicomweb_client.api import load_json_dataset
Sorry, I removed it.

2022-02-01 16:59 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    # from dicomweb_client.api import load_json_dataset
Thanks, I removed it.

2022-02-01 16:59 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      # serie = load_json_dataset(serieJson)
Thanks, I removed it.

2022-02-01 17:46 UTC, deepakri201 commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      if (version.parse(dicomweb_client.__version__) < version.parse("0.54")):
I believe that the Slicer 4.11 has the `dicomweb_client` version less than `0.54`, but the latest Preview release 4.13.0 uses version `0.54.4`.

2022-02-01 21:53 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +    return self.gcloud(f"--project {project} healthcare datasets list --format=value(ID,LOCATION)").split("\n")[0:]
I see, you added the `--format=value(ID,LOCATION)` so yes, there's no header row to strip off.  This looks good now.

2022-02-01 21:54 UTC, pieper commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      if (version.parse(dicomweb_client.__version__) < version.parse("0.54")):
Yes, makes sense.  We can leave this for now and remove it in the future.

2022-02-01 21:55 UTC, pieper approved these changes
LGTM 👍

2022-02-01 21:55 UTC, merged

2022-02-01 22:22 UTC, jamesobutler commented on DICOMwebBrowser/DICOMwebBrowser.py
> +      if (version.parse(dicomweb_client.__version__) < version.parse("0.54")):
```diff
-         dataset = load_json_dataset(data)
+         dataset = pydicom.dataset.Dataset.from_json(data)
```
Note that `pydicom` for current Slicer stable 4.11.20210226 is using version 2.0.0 also contains the `pydicom.dataset.Dataset.from_json` method. So you could seemingly switch to that method and have support for both current Slicer stable and the latest Slicer 4.13 preview.

https://github.com/pydicom/pydicom/blob/v2.2.2/pydicom/dataset.py#L2391